import { describe, expect, it } from "vitest";
import { z } from "zod";
import { UUID_PATTERN } from "@/lib/planning/sop";

/**
 * Regression cover for the /planning/new dead end: ticking an SOP item made the
 * form fail with "Check the highlighted fields" and nothing highlighted.
 *
 * The seeded SOP template ids come from `md5(key)::uuid`, so they are valid
 * Postgres uuids with no RFC 4122 version or variant bits. Zod 4's `.uuid()`
 * rejects 20 of the 28 live templates, and the resulting error key
 * (`sopNotRequiredTemplateIds.<index>`) matched no rendered input.
 *
 * These ids are real production values. A `gen_random_uuid()` fixture would
 * pass under the old strict schema and prove nothing.
 */
const MD5_DERIVED_TEMPLATE_IDS = [
  "c0905fb6-d04d-4c4a-0fec-3dc142ac7e49", // Staffing, variant nibble 0
  "059182f8-2be7-6e9f-6861-608ff5ba24fa" // Food specs, version nibble 6 and variant nibble 6
];

const RFC_CONFORMANT_TEMPLATE_ID = "9115f36f-3477-4257-80cb-514aba82071d"; // Setup Event

const sopTemplateIdSchema = z.string().regex(UUID_PATTERN, "Unrecognised SOP task");

describe("SOP template id validation", () => {
  it("rejects the md5-derived ids under zod's strict uuid rule, which is the bug", () => {
    const strict = z.string().uuid();
    for (const id of MD5_DERIVED_TEMPLATE_IDS) {
      expect(strict.safeParse(id).success).toBe(false);
    }
  });

  it("accepts the md5-derived ids under the shared lax pattern", () => {
    for (const id of MD5_DERIVED_TEMPLATE_IDS) {
      expect(sopTemplateIdSchema.safeParse(id).success).toBe(true);
    }
  });

  it("still accepts ids generated by gen_random_uuid", () => {
    expect(sopTemplateIdSchema.safeParse(RFC_CONFORMANT_TEMPLATE_ID).success).toBe(true);
  });

  it("rejects anything that is not uuid-shaped", () => {
    for (const value of ["", "not-a-uuid", "123", "c0905fb6d04d4c4a0fec3dc142ac7e49"]) {
      expect(sopTemplateIdSchema.safeParse(value).success).toBe(false);
    }
  });

  it("accepts a mixed selection of conformant and md5-derived ids", () => {
    const result = z
      .array(sopTemplateIdSchema)
      .safeParse([RFC_CONFORMANT_TEMPLATE_ID, ...MD5_DERIVED_TEMPLATE_IDS]);
    expect(result.success).toBe(true);
  });
});

describe("error keys the planning form can emit", () => {
  /** Mirrors zodFieldErrors in src/actions/planning.ts. */
  function zodFieldErrors(error: z.ZodError): Record<string, string> {
    const result: Record<string, string> = {};
    error.issues.forEach((issue) => {
      const key = issue.path.join(".") || "form";
      if (!result[key]) result[key] = issue.message;
    });
    return result;
  }

  it("keys array failures by an index that varies with the selection", () => {
    const schema = z.object({ sopNotRequiredTemplateIds: z.array(z.string().uuid()) });

    const firstFails = schema.safeParse({ sopNotRequiredTemplateIds: [MD5_DERIVED_TEMPLATE_IDS[0]] });
    const secondFails = schema.safeParse({
      sopNotRequiredTemplateIds: [RFC_CONFORMANT_TEMPLATE_ID, MD5_DERIVED_TEMPLATE_IDS[0]]
    });

    expect(Object.keys(zodFieldErrors(firstFails.error!))).toEqual(["sopNotRequiredTemplateIds.0"]);
    expect(Object.keys(zodFieldErrors(secondFails.error!))).toEqual(["sopNotRequiredTemplateIds.1"]);
  });

  it("matches an indexed key back to its field on the segment before the dot", () => {
    // This is the rule FormErrorSummary applies. Matching on the literal
    // "sopNotRequiredTemplateIds.0" would miss every other index.
    const handled = new Set(["title", "typeLabel", "targetDate", "venueId", "venueIds", "ownerId"]);
    const unmatched = ["sopNotRequiredTemplateIds.3", "title"].filter(
      (key) => !handled.has(key.split(".")[0])
    );
    expect(unmatched).toEqual(["sopNotRequiredTemplateIds.3"]);
  });
});
