-- Keep audit_log_action_check aligned with audit actions emitted by the app.
-- The constraint remains NOT VALID so historical rows are not rechecked during deploy.
alter table public.audit_log
  drop constraint if exists audit_log_action_check;

alter table public.audit_log
  add constraint audit_log_action_check check (action = any (array[
    'event.created', 'event.updated', 'event.artists_updated', 'event.submitted',
    'event.approved', 'event.needs_revisions', 'event.rejected', 'event.cancelled',
    'event.completed', 'event.assignee_changed', 'event.deleted', 'event.status_changed',
    'event.website_copy_generated', 'event.debrief_updated', 'event.terms_generated',
    'event.draft_saved', 'event.booking_settings_updated',
    'sop_section.created', 'sop_section.updated', 'sop_section.deleted',
    'sop_section.assignees_propagated',
    'sop_task_template.created', 'sop_task_template.updated', 'sop_task_template.deleted',
    'sop_task_template.assignees_propagated',
    'sop_dependency.created', 'sop_dependency.deleted', 'sop_checklist.generated',
    'sop_checklist.dates_recalculated', 'sop_backfill_completed',
    'planning.item_created', 'planning.item_updated', 'planning.item_deleted',
    'planning.series_created', 'planning.series_updated', 'planning.series_paused',
    'planning.task_created', 'planning.task_updated', 'planning.task_deleted',
    'planning_task.status_changed', 'planning_task.reassigned',
    'planning_task.dependency_added', 'planning_task.dependency_removed',
    'planning_task.notes_updated', 'planning_task.cascade_spawn',
    'planning_task.cascade_autocompleted', 'planning_task.cascade_reopened',
    'planning_task.debrief_created', 'planning_task.debrief_autocompleted',
    'planning_task.auto_not_required',
    'auth.login.success', 'auth.login.failure', 'auth.login.service_error',
    'auth.lockout', 'auth.logout', 'auth.password_reset.requested',
    'auth.password_updated', 'auth.invite.sent', 'auth.invite.accepted',
    'auth.invite.resent', 'auth.role.changed', 'auth.session.expired.idle',
    'auth.session.expired.absolute',
    'customer.erased',
    'booking.created', 'booking.updated', 'booking.cancelled',
    'user.deactivated', 'user.reactivated', 'user.deleted',
    'user.sensitive_column_changed', 'user.updated', 'user.central_lead_set',
    'user.preference_updated',
    'venue.created', 'venue.updated', 'venue.deleted',
    'artist.created', 'artist.updated', 'artist.archived', 'artist.restored',
    'event_type.created', 'event_type.updated', 'event_type.deleted',
    'link.created', 'link.updated', 'link.deleted', 'link.variant_created',
    'opening_hours.service_type_created', 'opening_hours.service_type_updated',
    'opening_hours.service_type_deleted', 'opening_hours.hours_saved',
    'opening_hours.multi_venue_hours_saved', 'opening_hours.override_created',
    'opening_hours.override_updated', 'opening_hours.override_deleted',
    'slt_member.added', 'slt_member.removed', 'slt_email.delivery_failed',
    'business_settings.updated',
    'attachment.uploaded', 'attachment.upload_failed', 'attachment.deleted',
    'attachment.version_added', 'attachment.renamed',
    'event.proposed', 'event.pre_approved', 'event.pre_rejected', 'event.pre_expired',
    'venue.category_changed', 'sop_task_template.expansion_changed',
    'planning.inspiration_dismissed', 'planning.inspiration_refreshed',
    'digest.batch_sent',
    'payment.order_created', 'payment.order_creation_failed', 'payment.captured',
    'payment.capture_failed', 'payment.capture_local_update_failed',
    'payment.refund_requested', 'payment.refund_completed',
    'payment.webhook_received', 'payment.webhook_processed',
    'sales_report.sent',
    'note.created', 'note.deleted',
    'booking.transfer_requested', 'booking.transferred', 'booking.transfer_email_failed',
    'event.cancellation_requested', 'event.cancelled_with_cascade', 'event.cancellation_failed',
    'event.rescheduled'
  ])) not valid;
